// Create the global registry if it doesn't exist
window.PRODUCT_REGISTRY = window.PRODUCT_REGISTRY || {
  configs: {},
  calculators: {},
};

// Register this product's configuration
window.PRODUCT_REGISTRY.configs["ASA SORF"] = {
  INPUT_COLS: ["B", "C", "D", "E", "F", "G", "H", "S", "T", "U", "Y"],
  INPUT_HEADERS: {
    B: "OD OF FLANGE (mm)",
    C: "ID (BORE) OF FLANGE (mm)",
    D: "FINAL THICKNESS (mm)",
    E: "NOS. OF HOLES",
    F: "HOLE DIA. (mm)",
    G: "R.F DIA",
    H: "FACE MACHINIG (1/2)",
    S: "PROFILE CUTTING RATE",
    T: "ID RATE",
    U: "CHIPS RATE",
    Y: "TOTAL M/C RATE",
  },
  ROWS: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
  ROW_LABELS: {
    8: "1/2''",
    9: "3/4''",
    10: "1''",
    11: '1.25"',
    12: "1.5''",
    13: '2"',
    14: "2.5''",
    15: "3''",
    16: "4''",
    17: "5''",
    18: "6''",
    19: "8''",
    20: "10''",
    21: '12"',
  },
  DEFAULTS: {
    8: {
      B: 89,
      C: 22.5,
      D: 11.7,
      E: 4,
      F: 16,
      G: 35,
      H: 1.5,
      S: 56,
      T: 35,
      U: 30,
      Y: 12,
    },
    9: {
      B: 98.5,
      C: 28.5,
      D: 12.7,
      E: 4,
      F: 16,
      G: 43,
      H: 1.5,
      S: 56,
      T: 35,
      U: 30,
      Y: 12,
    },
    10: {
      B: 108,
      C: 35.5,
      D: 14.5,
      E: 4,
      F: 16,
      G: 51,
      H: 1.5,
      S: 55,
      T: 35,
      U: 30,
      Y: 12,
    },
    11: {
      B: 117.5,
      C: 44,
      D: 16,
      E: 4,
      F: 16,
      G: 63.5,
      H: 1.5,
      S: 55,
      T: 35,
      U: 30,
      Y: 12,
    },
    12: {
      B: 127,
      C: 50.5,
      D: 17.5,
      E: 4,
      F: 16,
      G: 73,
      H: 1.5,
      S: 62,
      T: 35,
      U: 30,
      Y: 13,
    },
    13: {
      B: 152.4,
      C: 62,
      D: 19.1,
      E: 4,
      F: 19,
      G: 92,
      H: 1.5,
      S: 60.5,
      T: 35,
      U: 30,
      Y: 12,
    },
    14: {
      B: 177.8,
      C: 78,
      D: 22.5,
      E: 4,
      F: 19,
      G: 104.5,
      H: 1.5,
      S: 63,
      T: 35,
      U: 30,
      Y: 18,
    },
    15: {
      B: 190.5,
      C: 91.5,
      D: 23.8,
      E: 4,
      F: 19,
      G: 127,
      H: 1.5,
      S: 59.5,
      T: 38,
      U: 30,
      Y: 18,
    },
    16: {
      B: 228.5,
      C: 116,
      D: 23.8,
      E: 8,
      F: 19,
      G: 157,
      H: 1.5,
      S: 59.5,
      T: 42,
      U: 30,
      Y: 25,
    },
    17: {
      B: 254,
      C: 144,
      D: 23.8,
      E: 8,
      F: 22,
      G: 186,
      H: 1.5,
      S: 68,
      T: 50,
      U: 30,
      Y: 30,
    },
    18: {
      B: 279.4,
      C: 171.5,
      D: 25.4,
      E: 8,
      F: 22,
      G: 216,
      H: 1.5,
      S: 61.5,
      T: 50,
      U: 30,
      Y: 35,
    },
    19: {
      B: 343,
      C: 222,
      D: 28.6,
      E: 8,
      F: 22,
      G: 270,
      H: 2,
      S: 64.5,
      T: 50,
      U: 30,
      Y: 45,
    },
    20: {
      B: 406.4,
      C: 276,
      D: 30.2,
      E: 12,
      F: 25.4,
      G: 324,
      H: 2,
      S: 68.5,
      T: 50,
      U: 30,
      Y: 55,
    },
    21: {
      B: 482.6,
      C: 327,
      D: 31.8,
      E: 12,
      F: 25.4,
      G: 381,
      H: 2,
      S: 68.5,
      T: 50,
      U: 30,
      Y: 65,
    },
  },
  OUTPUT_ORDER: [
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "W",
    "R",
    "X",
    "V",
    "Z",
    "AA",
    "AB",
  ],
  OUTPUT_LABELS: {
    I: "OD OF CIRCLE (mm)",
    J: "THICKNESS OF CIRCLE (mm)",
    K: "CIRCLE WEIGHT (KG)",
    L: "ID CHIPS WEIGHT(KG)",
    M: "FACING CHIPS WEIGHT (KG)",
    N: "OD CHIPS WEIGHT (KG)",
    O: "HOLE CHIPS WEIGHT (KG)",
    P: "R.F CHIPS WEIGHT (KG)",
    Q: "TOTAL CHIPS WEIGHT    (KG)",
    W: "ID RATE",
    R: "ID WEIGHT",
    X: "RAW CIRCLE RATE",
    V: "SCRAP CHIPS RATE",
    Z: "MFG RATE",
    AA: "SELLING ",
    AB: "WEIGHT OF FLANGE",
  },
  PDF_SPEC_COLS: ["B", "C", "D", "E", "F", "G"],
};

// Register this product's calculation function
window.PRODUCT_REGISTRY.calculators["ASA SORF"] = function (
  IN,
  { n, PI, DENS }
) {
  const B = n(IN.B),
    C = n(IN.C),
    D = n(IN.D),
    E = n(IN.E),
    F = n(IN.F),
    G = n(IN.G),
    H = n(IN.H),
    S = n(IN.S),
    T = n(IN.T),
    U = n(IN.U),
    Y = n(IN.Y);
  const I = B + 4;
  const J = D + H;
  const K = ((1.02 * PI * I * I * J) / 4) * DENS;
  const L =
    ((PI * J * C * C) / 4) * DENS - ((PI * J * (C - 14) * (C - 14)) / 4) * DENS;
  const M = ((PI * H * B * B) / 4) * DENS - ((PI * H * C * C) / 4) * DENS;
  const N = ((PI * D * I * I) / 4) * DENS - ((PI * D * B * B) / 4) * DENS;
  const O = ((PI * F * F * D) / 4) * DENS * E;
  const P = ((PI * B * B) / 4) * DENS - ((PI * G * G) / 4) * DENS;
  const Q = L + M + N + O + P;
  const R = ((PI * J * (C - 14) * (C - 14)) / 4) * DENS;
  const V = Q * U * 0.95;
  const W = R * T * 0.98;
  const X = K * S;
  const Z = X + Y - W - V;
  const AA = Z * 1.1;
  const AB = K - R - Q;
  return { I, J, K, L, M, N, O, P, Q, R, V, W, X, Z, AA, AB };
};
