// Create the global registry if it doesn't exist
window.PRODUCT_REGISTRY = window.PRODUCT_REGISTRY || {
  configs: {},
  calculators: {},
};

// Register this product's configuration
window.PRODUCT_REGISTRY.configs["ASA-CL300-SORF"] = {
  INPUT_COLS: ["B", "C", "D", "E", "F", "G", "H", "S", "T", "U", "Y"],
  INPUT_HEADERS: {
    B: "OD OF FLANGE (mm)",
    C: "ID (BORE) OF FLANGE (mm)",
    D: "FINAL THICKNESS (mm)",
    E: "NOS. OF HOLES",
    F: "HOLE DIA. (mm)",
    G: "R.F DIA",
    H: "FACE MACHINIG (1/2)",
    S: "PROFILE CUTTING RATE",
    T: "ID SCRAP RATE",
    U: "CHIPS RATE",
    Y: "TOTAL M/C RATE",
  },

  ROWS: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

  ROW_LABELS: {
    8: "1/2''",
    9: "3/4''",
    10: "1''",
    11: "1.5''",
    12: "2''",
    13: "2.5''",
    14: "3''",
    15: "4''",
    16: "5''",
    17: "6''",
    18: "8''",
    19: "10''",
    20: "12''",
  },

  DEFAULTS: {
    8: {
      B: 95.25,
      C: 22.2,
      D: 11.7,
      E: 4,
      F: 16,
      G: 35,
      H: 1.5,
      S: 64,
      T: 39,
      U: 38,
      Y: 15,
    },
    9: {
      B: 117.5,
      C: 28.5,
      D: 14.28,
      E: 4,
      F: 19,
      G: 43,
      H: 1.5,
      S: 62,
      T: 39,
      U: 38,
      Y: 16,
    },
    10: {
      B: 123.8,
      C: 35.5,
      D: 16,
      E: 4,
      F: 19,
      G: 51,
      H: 1.5,
      S: 64,
      T: 39,
      U: 38,
      Y: 16,
    },
    11: {
      B: 155.6,
      C: 50.5,
      D: 20.5,
      E: 4,
      F: 22,
      G: 73,
      H: 1.5,
      S: 64,
      T: 39,
      U: 38,
      Y: 18,
    },
    12: {
      B: 165.0,
      C: 62.5,
      D: 22.2,
      E: 4,
      F: 22,
      G: 92,
      H: 1.5,
      S: 64,
      T: 39,
      U: 38,
      Y: 20,
    },
    13: {
      B: 190.5,
      C: 78.0,
      D: 25.5,
      E: 8,
      F: 22,
      G: 104.5,
      H: 1.5,
      S: 65,
      T: 39,
      U: 38,
      Y: 20,
    },
    14: {
      B: 209.6,
      C: 91.5,
      D: 28.6,
      E: 8,
      F: 22,
      G: 127,
      H: 1.5,
      S: 68,
      T: 50,
      U: 38,
      Y: 28,
    },
    15: {
      B: 254.0,
      C: 116.5,
      D: 31.8,
      E: 8,
      F: 22,
      G: 157,
      H: 1.5,
      S: 68.5,
      T: 55,
      U: 38,
      Y: 30,
    },
    16: {
      B: 279.4,
      C: 144.0,
      D: 35.0,
      E: 8,
      F: 22,
      G: 186,
      H: 1.5,
      S: 69,
      T: 55,
      U: 38,
      Y: 35,
    },
    17: {
      B: 317.5,
      C: 171.5,
      D: 36.5,
      E: 12,
      F: 22,
      G: 216,
      H: 2.0,
      S: 69.5,
      T: 55,
      U: 38,
      Y: 40,
    },
    18: {
      B: 381.0,
      C: 222.0,
      D: 41.3,
      E: 12,
      F: 25.4,
      G: 270,
      H: 2.0,
      S: 72,
      T: 55,
      U: 38,
      Y: 55,
    },
    19: {
      B: 444.5,
      C: 276.0,
      D: 47.6,
      E: 16,
      F: 28.6,
      G: 324,
      H: 2.0,
      S: 73,
      T: 55,
      U: 38,
      Y: 75,
    },
    20: {
      B: 520.7,
      C: 327.2,
      D: 50.8,
      E: 16,
      F: 30.0,
      G: 381,
      H: 2.0,
      S: 75,
      T: 55,
      U: 38,
      Y: 100,
    },
  },

  OUTPUT_ORDER: [
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "W",
    "R",
    "X",
    "V",
    "Z",
    "AA",
    "AB",
  ],
  OUTPUT_LABELS: {
    I: "OD OF CIRCLE (mm)",
    J: "THICKNESS OF CIRCLE (mm)",
    K: "CIRCLE WEIGHT (KG)",
    L: "ID CHIPS WEIGHT(KG)",
    M: "FACING CHIPS WEIGHT (KG)",
    N: "OD CHIPS WEIGHT (KG)",
    O: "HOLE CHIPS WEIGHT (KG)",
    P: "R.F CHIPS WEIGHT (KG)",
    Q: "TOTAL CHIPS WEIGHT    (KG)",
    W: "ID RATE",
    R: "ID WEIGHT",
    X: "RAW CIRCLE RATE",
    V: "SCRAP CHIPS RATE",
    Z: "MFG RATE",
    AA: "SELLING ",
    AB: "WEIGHT OF FLANGE",
  },
  PDF_SPEC_COLS: ["B", "C", "D", "E", "F", "G"],
};

// Register this product's calculation function
window.PRODUCT_REGISTRY.calculators["ASA-CL300-SORF"] = function (
  IN,
  { n, PI, DENS }
) {
  const B = n(IN.B),
    C = n(IN.C),
    D = n(IN.D),
    E = n(IN.E),
    F = n(IN.F),
    G = n(IN.G),
    H = n(IN.H),
    S = n(IN.S),
    T = n(IN.T),
    U = n(IN.U),
    Y = n(IN.Y);
  const I = B + 4;
  const J = D + H;
  const K = ((1.02 * PI * I * I * J) / 4) * DENS;
  const L =
    ((PI * J * (C + 13) * (C + 13)) / 4) * DENS - ((PI * J * C * C) / 4) * DENS;
  const M = ((PI * H * B * B) / 4) * DENS - ((PI * H * C * C) / 4) * DENS;
  const N = ((PI * D * I * I) / 4) * DENS - ((PI * D * B * B) / 4) * DENS;
  const O = ((PI * F * F * D) / 4) * DENS * E;
  const P = ((PI * 1 * B * B) / 4) * DENS - ((PI * 1 * G * G) / 4) * DENS;
  const Q = L + M + N + O + P;
  const R = ((PI * J * (C - 13) * (C - 13)) / 4) * DENS;
  const V = Q * U * 0.95;
  const W = R * T;
  const X = K * S;
  const Z = X + Y - W - V;
  const AA = Z * 1.1;
  const AB = K - R - Q;
  return { I, J, K, L, M, N, O, P, Q, R, V, W, X, Z, AA, AB };
};
